@tool
extends Node

################################################################################
#                        Copyright 2022-2023 ArchaicSoft                       #
#                                                                              #
# Boost Software License - Version 1.0 - August 17th, 2003                     #
#                                                                              #
# Permission is hereby granted, free of charge, to any person or organization  #
# obtaining a copy of the software and accompanying documentation covered by   #
# this license (the "Software") to use, reproduce, display, distribute,        #
# execute, and transmit the Software, and to prepare derivative works of the   #
# Software, and to permit third-parties to whom the Software is furnished to   #
# do so, all subject to the following:                                         #
#                                                                              #
# The copyright notices in the Software and this entire statement, including   #
# the above license grant, this restriction and the following disclaimer,      #
# must be included in all copies of the Software, in whole or in part, and     #
# all derivative works of the Software, unless such copies or derivative       #
# works are solely in the form of machine-executable object code generated by  #
# a source language processor.                                                 #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT    #
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    #
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  #
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  #
# DEALINGS IN THE SOFTWARE.                                                    #
################################################################################

func _set_resolution(x: int, y: int) -> void:
	ProjectSettings.set_setting("display/window/size/viewport_width", x)
	ProjectSettings.set_setting("display/window/size/viewport_height", y)

func _on_vga_pressed()         -> void: _set_resolution(640, 480)
func _on_crt_pressed()         -> void: _set_resolution(800, 600)
func _on_universal_pressed()   -> void: _set_resolution(1280, 720)
func _on_wide_screen_pressed() -> void: _set_resolution(1680, 1050)
func _on_desktop_pressed()     -> void: _set_resolution(1920, 1080)

func _on_2d_unblur_pressed() -> void:
	ProjectSettings.set_setting(
		"rendering/textures/canvas_textures/default_texture_filter",
		Window.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_NEAREST
	)

func _on_2d_blur_pressed()   -> void:
	ProjectSettings.set_setting(
		"rendering/textures/canvas_textures/default_texture_filter",
		Window.DEFAULT_CANVAS_ITEM_TEXTURE_FILTER_LINEAR
	)

func _pixel_snap(value: bool) -> void:
	ProjectSettings.set_setting("rendering/2d/snap/snap_2d_transforms_to_pixel", value)
	ProjectSettings.set_setting("rendering/2d/snap/snap_2d_vertices_to_pixel", value)

func _on_2d_snap_pixels_pressed()   -> void: _pixel_snap(true)
func _on_2d_unsnap_pixels_pressed() -> void: _pixel_snap(false)

func _xr_enabled(value: bool) -> void:
	ProjectSettings.set_setting("xr/openxr/enabled", value)
	ProjectSettings.set_setting("xr/shaders/enabled", value)

func _on_xr_enable_pressed()  -> void: _xr_enabled(true)
func _on_xr_disable_pressed() -> void: _xr_enabled(false)
