@tool
extends EditorPlugin

################################################################################
#                        Copyright 2022-2023 ArchaicSoft                       #
#                                                                              #
# Boost Software License - Version 1.0 - August 17th, 2003                     #
#                                                                              #
# Permission is hereby granted, free of charge, to any person or organization  #
# obtaining a copy of the software and accompanying documentation covered by   #
# this license (the "Software") to use, reproduce, display, distribute,        #
# execute, and transmit the Software, and to prepare derivative works of the   #
# Software, and to permit third-parties to whom the Software is furnished to   #
# do so, all subject to the following:                                         #
#                                                                              #
# The copyright notices in the Software and this entire statement, including   #
# the above license grant, this restriction and the following disclaimer,      #
# must be included in all copies of the Software, in whole or in part, and     #
# all derivative works of the Software, unless such copies or derivative       #
# works are solely in the form of machine-executable object code generated by  #
# a source language processor.                                                 #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT    #
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    #
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  #
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  #
# DEALINGS IN THE SOFTWARE.                                                    #
################################################################################

const Interface = preload("Interface.tscn")
var interface: Control

func _get_png_or_svg(path: String) -> String:
	var file : String
	
	file = path + ".svg"
	if FileAccess.file_exists(file): return file
	
	file = path + ".png"
	if FileAccess.file_exists(file): return file
	
	return ""

func _get_plugin_icon() -> Texture2D:
	return get_editor_interface().get_base_control().get_icon("Node", "EditorIcons")

func _enter_tree() -> void:
	_update_asset_lib_path()
	
	_init_interface()
	_init_directories()
	_relocate_assets()
	_generate_export_templates()
	_generate_resources()
	_generate_script_templates()
	_generate_session_src()
	_adjust_settings()
	_modify_git_ignore()

func _exit_tree() -> void:
	_kill_interface()

func _update_asset_lib_path() -> void:
	const ASSETS_PATH : String = "asset_library/available_urls"
	var e_settings    : EditorSettings = get_editor_interface().get_editor_settings()
	var repos         : Dictionary     = e_settings.get_setting(ASSETS_PATH)
	repos["archaicsoft (mirror)"] = "coming soon"
	e_settings.set_setting(ASSETS_PATH, repos)

func _init_interface() -> void:
	if is_instance_valid(interface): return
	interface = Interface.instantiate()
	add_control_to_dock(EditorPlugin.DOCK_SLOT_LEFT_UR, interface)

func _kill_interface() -> void:
	if not is_instance_valid(interface): return
	remove_control_from_docks(interface)
	interface.queue_free()

func _init_directories() -> void:
	var directories : Array[String] = [
		# base paths
		".export", "addons", "assets", "extensions",
		"resources", "scenes", "scripts",
		
		# export paths
		".export/linux", ".export/android",
		".export/win32", ".export/win64",
		".export/macos", ".export/ios",
		
		# asset base paths
		"assets/audio", "assets/fonts", "assets/images", "assets/models",
		
		# audio paths
		"assets/audio/music", "assets/audio/sound",
		
		# image paths
		"assets/images/characters", "assets/images/gui",
		"assets/images/system", "assets/images/tilesets",
		
		# resource paths
		"resources/materials", "resources/openxr", "resources/themes",
		
		# scene paths
		"scenes/screens",
		
		# script paths
		"scripts/templates"
	]
	
	for dir in directories:
		var path : String = "res://" + dir
		if not DirAccess.dir_exists_absolute(path):
			DirAccess.make_dir_recursive_absolute(path)

func _relocate_assets() -> void:
	var files : PackedStringArray = DirAccess.get_files_at("res://")
	
	# move source files
	for file in files:
		if file.ends_with(".gd"):
			DirAccess.rename_absolute(file, "res://scripts/" + file.get_file())
	
	var file : String
	
	# move project icon
	file = "res://icon.png"
	if FileAccess.file_exists(file):
		DirAccess.rename_absolute(file, "res://assets/images/system/icon.png")
	
	file = "res://icon.svg"
	if FileAccess.file_exists(file):
		DirAccess.rename_absolute(file, "res://assets/images/system/icon.svg")

func _generate_export_templates() -> void:
	var path : String = "res://export_presets.cfg"
	if not FileAccess.file_exists(path):
		var template_file : String = "res://addons/project_setup/export_presets.cfg"
		DirAccess.copy_absolute(template_file, path)
	
	path = "res://debug.keystore"
	if not FileAccess.file_exists(path):
		var template_file : String = "res://addons/project_setup/debug.keystore"
		DirAccess.copy_absolute(template_file, path)

func _generate_resources() -> void:
	var path : String
	
	# Audio Layout
	path  = "res://resources/audio_layout.tres"
	if not FileAccess.file_exists(path):
		var resource = AudioBusLayout.new()
		ResourceSaver.save(resource, path)
	
	# Environment
	path = "res://resources/environment.tres"
	if not FileAccess.file_exists(path):
		var resource = Environment.new()
		resource.background_mode = Environment.BG_SKY
		resource.sky = Sky.new()
		resource.sky.sky_material = ProceduralSkyMaterial.new()
		ResourceSaver.save(resource, path)
	
	# Theme
	path = "res://resources/themes/default.tres"
	if not FileAccess.file_exists(path):
		var resource = Theme.new()
		ResourceSaver.save(resource, path)

func _generate_script_templates() -> void:
	## ensure node templates exists
	var templates_dir : String = "res://addons/project_setup/templates/Node/"
	var template_path : String = "res://scripts/templates/Node/"
	
	# create missing directory
	if not DirAccess.dir_exists_absolute(template_path):
		DirAccess.make_dir_recursive_absolute(template_path)
	
	# copy missing templates
	for file_path in DirAccess.get_files_at(templates_dir):
		var template_file : String = template_path + file_path.get_file().left(-1)
		if not FileAccess.file_exists(template_file):
			DirAccess.copy_absolute(templates_dir + file_path, template_file)

func _generate_session_src() -> void: pass # disabled until proper check is discovered
	# var path : String = "res://scripts/session.gd"
	# if not FileAccess.file_exists(path):
	#	var file := FileAccess.open(path, FileAccess.WRITE)
	#	file.store_line("extends Node")
	#	file.flush()
	#	file = null
	
	# # register it in autoload
	# if not type_exists("Session"):
	#	add_autoload_singleton("Session", path)

func _adjust_settings() -> void:
	var file : String
	
	# set icon data
	file = _get_png_or_svg("res://assets/images/system/icon")
	if file != "": ProjectSettings.set_setting("application/config/icon", file)
	
	file = "res://assets/images/system/icon.icns"
	if FileAccess.file_exists(file):
		ProjectSettings.set_setting("application/config/macos_native_icon", file)
	
	file = "res://assets/images/system/icon.ico"
	if FileAccess.file_exists(file):
		ProjectSettings.set_setting("application/config/windows_native_icon", file)
	
	# set splash screen
	file = _get_png_or_svg("res://assets/images/system/splash")
	if file != "":
		ProjectSettings.set_setting("application/boot_splash/image", file)
		ProjectSettings.set_setting("application/boot_splash/show_image", true)
	
	# set mouse cursor image
	file = _get_png_or_svg("res://assets/images/system/cursor")
	if file != "": ProjectSettings.set_setting("display/mouse_cursor/custom_image", file)
	
	# set default audio bus layout
	ProjectSettings.set_setting("audio/buses/default_bus_layout", "res://resources/audio_layout.tres")
	
	# set default script templates
	ProjectSettings.set_setting("editor/script/templates_search_path", "res://scripts/templates")
	
	# set openxr action map
	ProjectSettings.set_setting("xr/openxr/default_action_map", "res://resources/openxr/action_map.tres")
	
	# set default environment
	ProjectSettings.set_setting("rendering/environment/defaults/default_environment", "res://resources/environment.tres")
	
	# set default theme
	ProjectSettings.set_setting("gui/theme/custom", "res://resources/themes/default.tres")

func _modify_git_ignore() -> void:
	var file := FileAccess.open("res://.gitignore", FileAccess.READ_WRITE)
	var contents = file.get_as_text()
	
	# scroll to end of file
	file.seek_end()
	
	# add export folder
	if not contents.contains("**/.export"):
		file.store_line("**/.export/")
	
	# add godot cache folder
	if not contents.contains("**/.godot"):
		file.store_line("**/.godot/")
	
	# todo: add any other default directories?
	##
	
	# complete the write and finish up
	file = null
