@tool
extends EditorPlugin

################################################################################
#                        Copyright 2022-2023 ArchaicSoft                       #
#                                                                              #
# Boost Software License - Version 1.0 - August 17th, 2003                     #
#                                                                              #
# Permission is hereby granted, free of charge, to any person or organization  #
# obtaining a copy of the software and accompanying documentation covered by   #
# this license (the "Software") to use, reproduce, display, distribute,        #
# execute, and transmit the Software, and to prepare derivative works of the   #
# Software, and to permit third-parties to whom the Software is furnished to   #
# do so, all subject to the following:                                         #
#                                                                              #
# The copyright notices in the Software and this entire statement, including   #
# the above license grant, this restriction and the following disclaimer,      #
# must be included in all copies of the Software, in whole or in part, and     #
# all derivative works of the Software, unless such copies or derivative       #
# works are solely in the form of machine-executable object code generated by  #
# a source language processor.                                                 #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT    #
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    #
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  #
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  #
# DEALINGS IN THE SOFTWARE.                                                    #
################################################################################

func _get_plugin_icon() -> Texture2D: return preload("icon.svg")

func _enter_tree() -> void:
	## ensure templates exists
	var templates_dir : String = "res://addons/network/templates/Network/"
	var template_path : String = ProjectSettings.get_setting("editor/script/templates_search_path")
	template_path += "/Network/" # add the category this uses
	
	# create missing directory
	if not DirAccess.dir_exists_absolute(template_path):
		DirAccess.make_dir_recursive_absolute(template_path)
	
	# copy missing templates
	for file_path in DirAccess.get_files_at(templates_dir):
		var template_file : String = template_path + file_path.get_file().left(-1)
		if not FileAccess.file_exists(template_file):
			DirAccess.copy_absolute(templates_dir + file_path, template_file)

func _exit_tree() -> void: pass
